<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260129141337 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE clients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tier_locked BOOLEAN DEFAULT NULL, tier_locked_value VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C82E7419EB6921 ON clients (client_id)');
        $this->addSql('CREATE TABLE rates (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_currency VARCHAR(3) NOT NULL, target_currency VARCHAR(3) NOT NULL, rate NUMERIC(18, 8) NOT NULL, valid_from DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_rates_pair_validfrom ON rates (source_currency, target_currency, valid_from)');
        $this->addSql('CREATE TABLE transactions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transaction_id VARCHAR(20) NOT NULL, amount NUMERIC(18, 2) NOT NULL, source_currency VARCHAR(3) NOT NULL, target_currency VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, refunded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, original_fee NUMERIC(18, 2) DEFAULT NULL, original_final_amount NUMERIC(18, 2) DEFAULT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EAA81A4C2FC0CB0F ON transactions (transaction_id)');
        $this->addSql('CREATE INDEX IDX_EAA81A4C19EB6921 ON transactions (client_id)');
        $this->addSql('CREATE INDEX idx_tx_client_createdat ON transactions (client_id, created_at)');
        $this->addSql('CREATE INDEX idx_tx_transaction_id ON transactions (transaction_id)');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4C19EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4C19EB6921');
        $this->addSql('DROP TABLE clients');
        $this->addSql('DROP TABLE rates');
        $this->addSql('DROP TABLE transactions');
    }
}
